/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook.batch.upload;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.ExpectedConditions;



/**
 *
 * @author josh
 */
public class PhonebookBatchUploadUI extends javax.swing.JFrame {

    /**
     * Creates new form RK17UI
     */
    public PhonebookBatchUploadUI() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel1.setText("Phonebook Uploader");
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jButton1.setText("Start");
        jButton1.setAutoscrolls(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 160, -1, -1));

        jLabel3.setText("Built by Joshua Olivier");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 260, -1, 20));

        jLabel2.setText("Version: 1.1.2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonebook/batch/upload/ezgif-3-e20ff87a9310.gif"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 50, -1, -1));

        jLabel5.setText("Designed for TotalSend.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/chris/Downloads/ezgif.com-crop.gif")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 297, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//In response to a button click:

 

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       
        // Create a file chooser instance whereby the user can select the relevant spreadsheet.
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            System.out.println(selectedFile.getAbsolutePath());
            String text1 = (selectedFile.getAbsolutePath());
            // Set up options for Chrome Webdriver.
            String downloadFilepath = "/Users/chris/Desktop/TFG 06 Dec";
            HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
            chromePrefs.put("profile.default_content_settings.popups", 0);
            chromePrefs.put("download.default_directory", downloadFilepath);
            ChromeOptions options = new ChromeOptions();
            options.setExperimentalOption("prefs", chromePrefs);
            DesiredCapabilities cap = DesiredCapabilities.chrome();
            cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
            cap.setCapability(ChromeOptions.CAPABILITY, options);
            WebDriver driver = new ChromeDriver(cap);

            driver.manage().window().maximize();
            // Load the login page of SayHi
            driver.get("https://console.sayhi.co.za/login/");

            // Find and populate the login Username.
            WebElement element = driver.findElement(By.id("id_username"));
            element.sendKeys("TFG_publish");

            // Find and populate the login password.
            WebElement element1 = driver.findElement(By.id("id_password"));
            element1.sendKeys("TFG_Publish@2018");

            // Find and click the login button.
            driver.findElement(By.cssSelector("button.btn.btn-primary")).click();
            // Start of Apache integration
            try {
                // Starts interacting with the selected excell sheet.
                FileInputStream fis = new FileInputStream(new File(text1));
                XSSFWorkbook workbook = new XSSFWorkbook(fis);

                XSSFSheet sheet = workbook.getSheetAt(0);

                Row row;
                for (int a = 1; a <= sheet.getLastRowNum(); a++) {
                    row = (Row) sheet.getRow(a);
                    // Set up strings to simplify code.
                    String one = row.getCell(0).getStringCellValue();
                    String two = one + " -> 0 contact(s)";
                    String path = "/Users/chris/Desktop/Uploads/";
                    String csv = ".csv";
                    String upload = path + one + csv;

                    driver.findElement(By.linkText("Contact")).click();

                    driver.findElement(By.linkText("Import Contacts")).click();

                    Select oSelect = new Select(driver.findElement(By.id("id_phonebook")));
                    oSelect.selectByVisibleText(two);

                    driver.findElement(By.cssSelector(".fa")).click();

                    WebElement uploadElement = driver.findElement(By.id("id_upload_file"));
                    uploadElement.sendKeys(upload);

                    driver.findElement(By.id("add")).click();

                    Select aSelect = new Select(driver.findElement(By.id("id_form-1-belong")));
                    aSelect.selectByVisibleText("full_name");

                    driver.findElement(By.id("add")).click();
                    
                    
                    WebDriverWait wait = new WebDriverWait(driver, 20);
                    
                    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("pre")));
                    
                }
            } catch (FileNotFoundException fnfe) {
                fnfe.printStackTrace();
            } catch (IOException ioe) {
                ioe.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhonebookBatchUploadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhonebookBatchUploadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhonebookBatchUploadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhonebookBatchUploadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhonebookBatchUploadUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
